import Link from "next/link";
type Scene={title:string;description:string;asset:string};
type Poster={title:string;asset:string};
type Section={number:string;title:string;type:"text"|"scenes"|"slots"|"posters";kicker:string;heading?:string;statement?:string;body?:string;english?:string;assets?:string[];scenes?:Scene[];posters?:Poster[]};
const sections:Section[]=[
 {number:"01",title:"The Place",type:"slots",kicker:"THE PLACE",heading:"从地方开始",statement:"这里从来不缺少内容。\n真正的问题，是如何理解它们之间的关系。",body:"现状历史建筑与公共文化资源主要沿中山大道与江汉路展开。近代金融建筑、商业地标、文化设施、历史里分与滨江空间彼此交织，共同构成今天可以被感知的汉口。",english:"Read the place before designing for it.",assets:["hankou-resource-map.webp","hankou-city.webp"]},
 {number:"02",title:"Frame",type:"slots",kicker:"FRAME",heading:"从资源到体验",statement:"街区不是一张景点清单。",body:"原有的信息可以被分成历史建筑、商业、美食、活动等类别，但这样的分类只说明“这里有什么”，并不能回答人应该如何进入和感知这个地方。\n因此，品牌叙事没有继续横向罗列资源，而是把一次街区漫游重新组织成连续发生的城市现场。",english:"From categories to experience.",assets:["hankou-narrative-map.webp"]},
 {number:"03",title:"Hankou Present",type:"text",kicker:"HANKOU PRESENT",heading:"汉口在场",statement:"长江来去，汉口在场。\n人来人往，百年如常。",body:"“在场”不是重新包装一段已经结束的历史，而是把注意力放回那些至今仍然发生的城市生活。"},
 {number:"04",title:"Four Scenes",type:"scenes",kicker:"FOUR SCENES",scenes:[{title:"商在场",description:"商业、金融与人的流动持续塑造着汉口。",asset:"hankou-scene-commerce.webp"},{title:"街在场",description:"建筑、里分与街巷保存时间，也继续容纳今天的生活。",asset:"hankou-scene-street.webp"},{title:"味在场",description:"地方味道发生在街角、店铺与人与人的日常往来中。",asset:"hankou-scene-flavor.webp"},{title:"戏在场",description:"演出、娱乐与公共生活让街区始终保持正在发生的状态。",asset:"hankou-scene-performance.webp"}]},
 {number:"05",title:"Visual Language",type:"slots",kicker:"VISUAL LANGUAGE",heading:"把地方转化为可识别的语言",body:"视觉系统从街区建筑、地方饮食、器物与文化意象中提取可识别的图形线索，再重新组合为一套具有统一关系、同时允许差异化表达的视觉语言。",english:"A place becomes recognizable through what people repeatedly see, remember and use.\n\nPlace → Symbol → System",assets:["symbol-window.svg","symbol-gate.svg","symbol-food.svg","symbol-pipa.svg"]},
 {number:"06",title:"Poster System",type:"posters",kicker:"POSTER SYSTEM",heading:"四张海报",posters:[{title:"商通四海",asset:"hankou-poster-commerce.webp"},{title:"街走百年",asset:"hankou-poster-street.webp"},{title:"百味生香",asset:"hankou-poster-flavor.webp"},{title:"万象开场",asset:"hankou-poster-performance.webp"}]},
 {number:"07",title:"Into the Street",type:"slots",kicker:"INTO THE STREET",body:"品牌语言随后进入真实的街区场景：建筑界面、墙面海报、悬挂旗帜与地面图形，使视觉识别不再只是平面传播，而成为人在步行过程中持续遇见的一部分。",english:"A visual identity matters when it begins to live in the place itself.",assets:["hankou-street-facade.webp","hankou-street-banner.webp","hankou-street-ground.webp"]},
 {number:"08",title:"Into Daily Life",type:"slots",kicker:"INTO DAILY LIFE",body:"品牌进一步进入可以被携带、使用、赠送和留下的日常物件。手提袋、包装、酒瓶、杯子以及小型周边延续同一套图形与色彩系统，让街区形象从公共空间进入更私人、更日常的使用场景。",english:"From something you see to something you keep.",assets:["hankou-daily-bag.webp","hankou-daily-package.webp","hankou-daily-bottle.webp","hankou-daily-cup.webp"]},
 {number:"09",title:"Digital Experience",type:"slots",kicker:"DIGITAL EXPERIENCE",body:"数字端继续承担同一个问题：如何让人进入街区，而不是只得到一份信息列表。现有 APP 概念包含品牌入口、街区探索、游览行程与地方饮食等内容，并通过不同路线和街区主题，把分散的地点与体验继续组织进一次实际的游览过程。",english:"Explore the city through places, routes and everyday life.",assets:["hankou-app-discover.webp","hankou-app-explore.webp","hankou-app-routes.webp","hankou-app-local-life.webp"]}
];
function Copy({s}:{s:Section}){return <div className="section-copy"><span className="section-kicker">{s.kicker}</span>{s.heading&&<h2>{s.heading}</h2>}{s.statement&&<p className="statement">{s.statement}</p>}{s.body&&<p className="body">{s.body}</p>}{s.english&&<p className="section-english">{s.english}</p>}</div>}
export default function Hankou(){return <main className="hankou"><header className="project-header"><Link href="/">← Home</Link><span>HANKOU PRESENT</span><span>WUHAN · 2026</span></header><section className="project-intro"><p className="eyebrow">NEIGHBORHOOD BRANDING · CULTURAL RESEARCH · VISUAL SYSTEM · EXPERIENCE DESIGN</p><h1>HANKOU PRESENT<br/><span>汉口在场</span></h1><p>Wuhan · 2026</p><p className="summary">江汉路与中山大道一带汇集了近代金融建筑、商业地标、历史里分、地方饮食、文化设施与滨江公共空间。这个项目从街区已有的文化与生活资源出发，重新组织人认识和经历汉口的方式，并将这一叙事继续转化为视觉识别、街区场景、周边产品与数字体验。</p><p className="question">How can a historic district be experienced as a living place, rather than a collection of attractions?</p></section><nav className="project-index">{sections.map(s=><a href={`#section-${s.number}`} key={s.number}><span>{s.number}</span>{s.title}</a>)}</nav>{sections.map(s=><section className={`hankou-section section-${s.number}`} id={`section-${s.number}`} key={s.number}><Copy s={s}/>{s.type==="scenes"&&<div className="asset-slot scenes">{s.scenes?.map(scene=><figure key={scene.asset}><div className="slot-box"><span>Asset slot</span><figcaption>{scene.asset}</figcaption></div><h3>{scene.title}</h3><p>{scene.description}</p></figure>)}</div>}{(s.type==="slots"||s.type==="posters")&&<div className="asset-slot slots">{s.type==="posters"?s.posters?.map(poster=><figure key={poster.asset}><span>Asset slot</span><figcaption>{poster.asset}</figcaption><h3>{poster.title}</h3></figure>):s.assets?.map(asset=><figure key={asset}><span>Asset slot</span><figcaption>{asset}</figcaption></figure>)}</div>}</section>)}<footer><Link href="/">← Back to Home</Link><a href="mailto:wenshin66@outlook.com">wenshin66@outlook.com</a></footer></main>}
