import Link from "next/link";
type Scene={title:string;description:string;asset:string;alt:string};
type Poster={title:string;asset:string};
type Section={number:string;title:string;type:"text"|"scenes"|"slots"|"posters";kicker:string;heading?:string;statement?:string;body?:string;english?:string;assets?:string[];scenes?:Scene[];posters?:Poster[]};
const sections:Section[]=[
 {number:"01",title:"The Place",type:"slots",kicker:"THE PLACE",heading:"从地方开始",body:"江汉路与中山大道一带的历史建筑、商业、里分、文化设施与滨江空间彼此交织，共同构成今天仍然可以被感知的汉口。",assets:["hankou-resource-map.webp"]},
 {number:"02",title:"Frame",type:"slots",kicker:"FRAME",heading:"从资源到体验",body:"不再把街区理解为景点与资源的分类，而是把分散的地点重新组织成一次连续发生的城市体验。",assets:["hankou-narrative-map.webp"]},
 {number:"03",title:"Hankou Present",type:"text",kicker:"HANKOU PRESENT",heading:"汉口在场",body:"长江来去，汉口在场；人来人往，百年如常。"},
 {number:"04",title:"Four Scenes",type:"scenes",kicker:"FOUR SCENES",scenes:[{title:"商在场",description:"商业、金融与人的流动持续塑造着汉口。",asset:"hankou-scene-commerce.webp",alt:"汉口夜间商业街与人群"},{title:"街在场",description:"建筑、里分与街巷保存时间，也继续容纳今天的生活。",asset:"hankou-scene-street.webp",alt:"武汉里分街区与红瓦屋顶"},{title:"味在场",description:"地方味道发生在街角、店铺与人与人的日常往来中。",asset:"hankou-scene-flavor.webp",alt:"汉口街边餐饮与日常生活场景"},{title:"戏在场",description:"演出、娱乐与公共生活让街区始终保持正在发生的状态。",asset:"hankou-scene-performance.webp",alt:"汉口夜间现场演出与观众"}]},
 {number:"05",title:"Visual Language",type:"slots",kicker:"VISUAL LANGUAGE",heading:"把地方变成可识别的语言",body:"从建筑、街巷、饮食与文化器物中提取图形线索，形成可以持续延展的视觉符号系统。",assets:["hankou-visual-language-overview.webp","symbol-window.svg","symbol-gate.svg","symbol-food.svg","symbol-pipa.svg"]},
 {number:"06",title:"Poster System",type:"posters",kicker:"POSTER SYSTEM",heading:"四个城市现场",posters:[{title:"商通四海",asset:"hankou-poster-commerce.webp"},{title:"街走百年",asset:"hankou-poster-street.webp"},{title:"百味生香",asset:"hankou-poster-flavor.webp"},{title:"万象登场",asset:"hankou-poster-performance.webp"}]},
 {number:"07",title:"Into the Street",type:"slots",kicker:"INTO THE STREET",heading:"让视觉进入真实街道",body:"海报、旗帜与地面图形进入建筑界面和步行空间，让品牌成为人在街区中持续遇见的一部分。",assets:["hankou-street-facade.webp","hankou-street-banner.webp","hankou-street-ground.webp"]},
 {number:"08",title:"Into Daily Life",type:"slots",kicker:"INTO DAILY LIFE",heading:"从看到，到带走",body:"品牌进一步进入包装、饮品与可以被携带和留下的日常物件。",assets:["hankou-daily-overview.webp"]},
 {number:"09",title:"Digital Experience",type:"slots",kicker:"DIGITAL EXPERIENCE",heading:"把街区继续组织进一次游览",body:"数字端通过地点、路线与地方生活内容，把分散的信息继续组织成一次可以实际进入的街区体验。",assets:["hankou-app-discover.webp","hankou-app-explore.webp","hankou-app-routes.webp","hankou-app-local-life.webp"]}
];
const REAL_ASSETS=new Set(["hankou-resource-map.webp","hankou-narrative-map.webp","hankou-scene-commerce.webp","hankou-scene-street.webp","hankou-scene-flavor.webp","hankou-scene-performance.webp"]);
const REAL_ALT:Record<string,string>={
 "hankou-resource-map.webp":"汉口江汉路—中山大道一带历史建筑与公共文化资源分布图",
 "hankou-narrative-map.webp":"汉口在场品牌叙事与街区体验框架图"
};
function Copy({s}:{s:Section}){return <div className="section-copy"><span className="section-kicker">{s.kicker}</span>{s.heading&&<h2>{s.heading}</h2>}{s.statement&&<p className="statement">{s.statement}</p>}{s.body&&<p className="body">{s.body}</p>}{s.english&&<p className="section-english">{s.english}</p>}</div>}
export default function Hankou(){return <main className="hankou"><header className="project-header"><Link href="/">← Home</Link><span>HANKOU PRESENT</span><span>WUHAN · 2026</span></header><section className="project-intro"><h1>HANKOU PRESENT <span>汉口在场</span></h1><p className="eyebrow">NEIGHBORHOOD BRANDING · CULTURAL RESEARCH · VISUAL SYSTEM · EXPERIENCE DESIGN · WUHAN · 2026</p><p className="summary">江汉路与中山大道一带汇集了近代金融建筑、商业地标、历史里分、地方饮食、文化设施与滨江公共空间。这个项目从街区已有的文化与生活资源出发，重新组织人认识和经历汉口的方式，并将这一叙事继续转化为视觉识别、街区场景、周边产品与数字体验。</p></section>{sections.map(s=><section className={`hankou-section section-${s.number}`} id={`section-${s.number}`} key={s.number}>{["01","02","03"].includes(s.number)&&<Copy s={s}/>} {s.number==="01"&&<div className="place-map"><img src="/images/hankou/hankou-resource-map.webp" alt={REAL_ALT["hankou-resource-map.webp"]} width="1600" height="1000" /></div>} {s.number==="02"&&<div className="narrative-map"><img src="/images/hankou/hankou-narrative-map.webp" alt={REAL_ALT["hankou-narrative-map.webp"]} width="1600" height="1000" /></div>} {s.number==="04"&&<><div className="scenes-intro"><span>{s.kicker}</span></div><div className="editorial-scenes">{s.scenes?.map((scene,index)=><figure className={`scene scene-${index+1}`} key={scene.asset}><img src={`/images/hankou/${scene.asset}`} alt={scene.alt} width="1122" height="1402" /><figcaption><h3>{scene.title}</h3><p>{scene.description}</p></figcaption></figure>)}</div></>} {(s.number!=="01"&&s.number!=="02"&&s.number!=="03"&&s.number!=="04"&&(s.type==="slots"||s.type==="posters"))&&<><Copy s={s}/><div className="asset-slot slots">{s.type==="posters"?s.posters?.map(poster=><figure key={poster.asset}><span>Asset slot</span><figcaption>{poster.asset}</figcaption><h3>{poster.title}</h3></figure>):s.assets?.map(asset=><figure key={asset}>{REAL_ASSETS.has(asset)?<img src={`/images/hankou/${asset}`} alt="" width="1600" height="1000" />:<div className="placeholder-box">Asset slot</div>}<figcaption>{asset}</figcaption></figure>)}</div></>}</section>)}<footer><Link href="/">← Back to Home</Link><a href="mailto:wenshin66@outlook.com">wenshin66@outlook.com</a></footer></main>}
